name: test

on:
  push:
    branches: [test]

concurrency:
  group: ci-testing-${{ github.ref }}
  cancel-in-progress: false

jobs:

  package:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: fpm
        run: |
          gem install fpm
          fpm --version

      - name: download
        run: |
          wget -c https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
          wget -c https://github.com/prometheus/node_exporter/releases/download/v1.3.1/sha256sums.txt
          sha256sum --check --ignore-missing sha256sums.txt

      - name: systemd
        run: |
          cat >node_exporter.service <<EOF
          # https://github.com/prometheus/node_exporter/blob/master/examples/systemd/node_exporter.service
          [Unit]
          Description=Node Exporter

          [Service]
          User=node_exporter
          EnvironmentFile=/etc/sysconfig/node_exporter
          ExecStart=/usr/sbin/node_exporter $OPTIONS

          [Install]
          WantedBy=multi-user.target
          EOF

      - name: package
        run: |
          tar xvfz node_exporter-*.*-amd64.tar.gz
          mv node_exporter-*.*-amd64/* .
          fpm \
            --input-type dir \
            --output-type deb \
            --prefix /usr/local/bin \
            --name node_exporter \
            --architecture amd64 \
            --version 1.3.1 \
            LICENSE=/usr/share/doc/node-exporter/LICENSE \
            NOTICE=/usr/share/doc/node-exporter/NOTICE \
            node_exporter=/usr/local/bin/node_exporter \
            node_exporter.service=/etc/systemd/system/node_exporter.service
          ls -l
          dpkg --contents node-exporter_1.3.1_amd64.deb

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          # passphrase: ${{ secrets.PASSPHRASE }}

      # https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html
      - name: ppa
        run: |
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          # https://github.com/keybase/keybase-issues/issues/2798
          export GPG_TTY=$(tty)
          # gpg --armor --export "${EMAIL}" > KEY.gpg
          # sudo apt update
          sudo apt install --yes dpkg-sig
          dpkg-sig -k "${EMAIL}" --sign builder node-exporter_1.3.1_amd64.deb
          echo "deb https://${GITHUB_REPOSITORY_OWNER}.github.io/node-exporter ./" \
            >"${GITHUB_REPOSITORY_OWNER}-node-exporter.list"
          ls -l
          cat "${GITHUB_REPOSITORY_OWNER}-node-exporter.list"
        env:
          EMAIL: mamercad+signing@gmail.com

      - name: commit
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Mark Mercado
          author_email: mamercad+signing@gmail.com
          message: Adding node-exporter_1.3.1_amd64.deb
          add: node-exporter_1.3.1_amd64.deb
          new_branch: ppa
          push: true
