name: test

on:
  push:
    branches: [test]

concurrency:
  group: ci-testing-${{ github.ref }}
  cancel-in-progress: false

jobs:

  fpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: fpm
        run: |
          gem install fpm
          fpm --version

      - name: download
        run: |
          wget -c https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
          wget -c https://github.com/prometheus/node_exporter/releases/download/v1.3.1/sha256sums.txt
          sha256sum --check --ignore-missing sha256sums.txt

      - name: package
        run: |
          tar xvfz node_exporter-*.*-amd64.tar.gz
          cd node_exporter-*.*-amd64
          fpm \
            --input-type dir \
            --output-type deb \
            --prefix /usr/local/bin \
            --name node_exporter \
            --architecture amd64 \
            --version 1.3.1 \
            node_exporter-LICENSE=/usr/local/bin/node_exporter-LICENSE \
            node_exporter-NOTICE=/usr/local/bin/node_exporter-NOTICE \
            node_exporter=/usr/local/bin/node_exporter
          ls -l
          dpkg --contents node-exporter_1.3.1_amd64.deb
