name: test

on:
  push:
    branches: [test]

concurrency:
  group: ci-testing-${{ github.ref }}
  cancel-in-progress: false

jobs:

  fpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: fpm
        run: |
          gem install fpm
          fpm --version

      - name: download
        run: |
          wget -c https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
          wget -c https://github.com/prometheus/node_exporter/releases/download/v1.3.1/sha256sums.txt
          sha256sum --check --ignore-missing sha256sums.txt

      - name: systemd
        run: |
          cat >node_exporter.service <<EOF
          # https://github.com/prometheus/node_exporter/blob/master/examples/systemd/node_exporter.service
          [Unit]
          Description=Node Exporter

          [Service]
          User=node_exporter
          EnvironmentFile=/etc/sysconfig/node_exporter
          ExecStart=/usr/sbin/node_exporter $OPTIONS

          [Install]
          WantedBy=multi-user.target
          EOF

      - name: package
        run: |
          tar xvfz node_exporter-*.*-amd64.tar.gz
          cd node_exporter-*.*-amd64
          cp ../node_exporter.service .
          fpm \
            --input-type dir \
            --output-type deb \
            --prefix /usr/local/bin \
            --name node_exporter \
            --architecture amd64 \
            --version 1.3.1 \
            LICENSE=/usr/local/bin/node_exporter-LICENSE \
            NOTICE=/usr/local/bin/node_exporter-NOTICE \
            node_exporter=/usr/local/bin/node_exporter \
            node_exporter.service=/etc/systemd/system/node_exporter.service
          ls -l
          dpkg --contents node-exporter_1.3.1_amd64.deb
