name: test

on:
  push:
    branches: [test]

concurrency:
  group: ci-testing-${{ github.ref }}
  cancel-in-progress: false

jobs:

  fpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: fpm
        run: |
          gem install fpm
          fpm --version
